[toolchain]
# Stable
channel = "1.81.0"
# Nightly
#channel = "nightly-2024-02-05" # rustc 1.78.0-nightly (f067fd608 2024-02-05)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]